version: "2.4"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: no 
    ports:
      - "8081:8081"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html  