version: "2.4"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: no 
    ports:
      - "8080:81"
    volumes:
      - ./conf:/etc/nginx
      - ./html:/usr/share/nginx/html  